using System;
using System.Collections.Generic;
using System.Text;

namespace Discord.Rest;

[Flags]
public enum PublicFlags : ulong
{
    STAFF = 1UL << 0,
    PARTNER = 1UL << 1,
    HYPESQUAD = 1UL << 2,
    BUG_HUNTER_LEVEL_1 = 1UL << 3,
    MFA_SMS = 1UL << 4,
    PREMIUM_PROMO_DISMISSED = 1UL << 5,
    HYPESQUAD_ONLINE_HOUSE_1 = 1UL << 6,
    HYPESQUAD_ONLINE_HOUSE_2 = 1UL << 7,
    HYPESQUAD_ONLINE_HOUSE_3 = 1UL << 8,
    PREMIUM_EARLY_SUPPORTER = 1UL << 9,
    TEAM_PSEUDO_USER = 1UL << 10,
    IS_HUBSPOT_CONTACT = 1UL << 11,
    HAS_UNREAD_URGENT_MESSAGES = 1UL << 13,
    BUG_HUNTER_LEVEL_2 = 1UL << 14,
    UNDERAGE_DELETED = 1UL << 15,
    VERIFIED_BOT = 1UL << 16,
    VERIFIED_DEVELOPER = 1UL << 17,
    CERTIFIED_MODERATOR = 1UL << 18,
    BOT_HTTP_INTERACTIONS = 1UL << 19,
    SPAMMER = 1UL << 20,
    PROVISIONAL_ACCOUNT = 1UL << 23,
    HIGH_GLOBAL_RATE_LIMIT = 1UL << 33,
    DELETED = 1UL << 34,
    DISABLED_SUSPICIOUS_ACTIVITY = 1UL << 35,
    SELF_DELETED = 1UL << 36,
    PREMIUM_DISCRIMINATOR = 1UL << 37,
    USED_DESKTOP_CLIENT = 1UL << 38,
    USED_WEB_CLIENT = 1UL << 39,
    USED_MOBILE_CLIENT = 1UL << 40,
    DISABLED = 1UL << 41,
    HAS_SESSION_STARTED = 1UL << 43,
    QUARANTINED = 1UL << 44,
    PREMIUM_ELIGIBLE_FOR_UNIQUE_USERNAME = 1UL << 47,
    COLLABORATOR = 1UL << 50,
    RESTRICTED_COLLABORATOR = 1UL << 51
}
